// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonProtos.proto

package com.steamcommunity.siplus.steamscreenshots.proto;

public final class CommonProtos {
  private CommonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeaderProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional fixed64 steamID = 1;
    /**
     * <code>optional fixed64 steamID = 1;</code>
     */
    boolean hasSteamID();
    /**
     * <code>optional fixed64 steamID = 1;</code>
     */
    long getSteamID();

    // optional int32 clientSessionID = 2;
    /**
     * <code>optional int32 clientSessionID = 2;</code>
     */
    boolean hasClientSessionID();
    /**
     * <code>optional int32 clientSessionID = 2;</code>
     */
    int getClientSessionID();

    // optional uint32 routingAppID = 3;
    /**
     * <code>optional uint32 routingAppID = 3;</code>
     */
    boolean hasRoutingAppID();
    /**
     * <code>optional uint32 routingAppID = 3;</code>
     */
    int getRoutingAppID();

    // optional fixed64 jobIDSource = 10 [default = 18446744073709551615];
    /**
     * <code>optional fixed64 jobIDSource = 10 [default = 18446744073709551615];</code>
     */
    boolean hasJobIDSource();
    /**
     * <code>optional fixed64 jobIDSource = 10 [default = 18446744073709551615];</code>
     */
    long getJobIDSource();

    // optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];
    /**
     * <code>optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];</code>
     */
    boolean hasJobIDTarget();
    /**
     * <code>optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];</code>
     */
    long getJobIDTarget();

    // optional string targetJobName = 12;
    /**
     * <code>optional string targetJobName = 12;</code>
     */
    boolean hasTargetJobName();
    /**
     * <code>optional string targetJobName = 12;</code>
     */
    java.lang.String getTargetJobName();
    /**
     * <code>optional string targetJobName = 12;</code>
     */
    com.google.protobuf.ByteString
        getTargetJobNameBytes();

    // optional int32 eresult = 13 [default = 2];
    /**
     * <code>optional int32 eresult = 13 [default = 2];</code>
     */
    boolean hasEresult();
    /**
     * <code>optional int32 eresult = 13 [default = 2];</code>
     */
    int getEresult();

    // optional string errorMessage = 14;
    /**
     * <code>optional string errorMessage = 14;</code>
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string errorMessage = 14;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string errorMessage = 14;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    // optional uint32 ip = 15;
    /**
     * <code>optional uint32 ip = 15;</code>
     */
    boolean hasIp();
    /**
     * <code>optional uint32 ip = 15;</code>
     */
    int getIp();

    // optional uint32 authAccountFlags = 16;
    /**
     * <code>optional uint32 authAccountFlags = 16;</code>
     */
    boolean hasAuthAccountFlags();
    /**
     * <code>optional uint32 authAccountFlags = 16;</code>
     */
    int getAuthAccountFlags();

    // optional int32 transportError = 17 [default = 1];
    /**
     * <code>optional int32 transportError = 17 [default = 1];</code>
     */
    boolean hasTransportError();
    /**
     * <code>optional int32 transportError = 17 [default = 1];</code>
     */
    int getTransportError();

    // optional uint64 messageID = 18 [default = 18446744073709551615];
    /**
     * <code>optional uint64 messageID = 18 [default = 18446744073709551615];</code>
     */
    boolean hasMessageID();
    /**
     * <code>optional uint64 messageID = 18 [default = 18446744073709551615];</code>
     */
    long getMessageID();

    // optional uint32 publisherGroupID = 19;
    /**
     * <code>optional uint32 publisherGroupID = 19;</code>
     */
    boolean hasPublisherGroupID();
    /**
     * <code>optional uint32 publisherGroupID = 19;</code>
     */
    int getPublisherGroupID();

    // optional uint32 sysID = 20;
    /**
     * <code>optional uint32 sysID = 20;</code>
     */
    boolean hasSysID();
    /**
     * <code>optional uint32 sysID = 20;</code>
     */
    int getSysID();

    // optional uint64 traceTag = 21;
    /**
     * <code>optional uint64 traceTag = 21;</code>
     */
    boolean hasTraceTag();
    /**
     * <code>optional uint64 traceTag = 21;</code>
     */
    long getTraceTag();
  }
  /**
   * Protobuf type {@code com.steamcommunity.siplus.steamscreenshots.proto.HeaderProto}
   */
  public static final class HeaderProto extends
      com.google.protobuf.GeneratedMessage
      implements HeaderProtoOrBuilder {
    // Use HeaderProto.newBuilder() to construct.
    private HeaderProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeaderProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeaderProto defaultInstance;
    public static HeaderProto getDefaultInstance() {
      return defaultInstance;
    }

    public HeaderProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeaderProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              steamID_ = input.readFixed64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clientSessionID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              routingAppID_ = input.readUInt32();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000008;
              jobIDSource_ = input.readFixed64();
              break;
            }
            case 89: {
              bitField0_ |= 0x00000010;
              jobIDTarget_ = input.readFixed64();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000020;
              targetJobName_ = input.readBytes();
              break;
            }
            case 104: {
              bitField0_ |= 0x00000040;
              eresult_ = input.readInt32();
              break;
            }
            case 114: {
              bitField0_ |= 0x00000080;
              errorMessage_ = input.readBytes();
              break;
            }
            case 120: {
              bitField0_ |= 0x00000100;
              ip_ = input.readUInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00000200;
              authAccountFlags_ = input.readUInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00000400;
              transportError_ = input.readInt32();
              break;
            }
            case 144: {
              bitField0_ |= 0x00000800;
              messageID_ = input.readUInt64();
              break;
            }
            case 152: {
              bitField0_ |= 0x00001000;
              publisherGroupID_ = input.readUInt32();
              break;
            }
            case 160: {
              bitField0_ |= 0x00002000;
              sysID_ = input.readUInt32();
              break;
            }
            case 168: {
              bitField0_ |= 0x00004000;
              traceTag_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.internal_static_com_steamcommunity_siplus_steamscreenshots_proto_HeaderProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.internal_static_com_steamcommunity_siplus_steamscreenshots_proto_HeaderProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto.class, com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto.Builder.class);
    }

    public static com.google.protobuf.Parser<HeaderProto> PARSER =
        new com.google.protobuf.AbstractParser<HeaderProto>() {
      public HeaderProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeaderProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeaderProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional fixed64 steamID = 1;
    public static final int STEAMID_FIELD_NUMBER = 1;
    private long steamID_;
    /**
     * <code>optional fixed64 steamID = 1;</code>
     */
    public boolean hasSteamID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional fixed64 steamID = 1;</code>
     */
    public long getSteamID() {
      return steamID_;
    }

    // optional int32 clientSessionID = 2;
    public static final int CLIENTSESSIONID_FIELD_NUMBER = 2;
    private int clientSessionID_;
    /**
     * <code>optional int32 clientSessionID = 2;</code>
     */
    public boolean hasClientSessionID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 clientSessionID = 2;</code>
     */
    public int getClientSessionID() {
      return clientSessionID_;
    }

    // optional uint32 routingAppID = 3;
    public static final int ROUTINGAPPID_FIELD_NUMBER = 3;
    private int routingAppID_;
    /**
     * <code>optional uint32 routingAppID = 3;</code>
     */
    public boolean hasRoutingAppID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 routingAppID = 3;</code>
     */
    public int getRoutingAppID() {
      return routingAppID_;
    }

    // optional fixed64 jobIDSource = 10 [default = 18446744073709551615];
    public static final int JOBIDSOURCE_FIELD_NUMBER = 10;
    private long jobIDSource_;
    /**
     * <code>optional fixed64 jobIDSource = 10 [default = 18446744073709551615];</code>
     */
    public boolean hasJobIDSource() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional fixed64 jobIDSource = 10 [default = 18446744073709551615];</code>
     */
    public long getJobIDSource() {
      return jobIDSource_;
    }

    // optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];
    public static final int JOBIDTARGET_FIELD_NUMBER = 11;
    private long jobIDTarget_;
    /**
     * <code>optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];</code>
     */
    public boolean hasJobIDTarget() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];</code>
     */
    public long getJobIDTarget() {
      return jobIDTarget_;
    }

    // optional string targetJobName = 12;
    public static final int TARGETJOBNAME_FIELD_NUMBER = 12;
    private java.lang.Object targetJobName_;
    /**
     * <code>optional string targetJobName = 12;</code>
     */
    public boolean hasTargetJobName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string targetJobName = 12;</code>
     */
    public java.lang.String getTargetJobName() {
      java.lang.Object ref = targetJobName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetJobName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string targetJobName = 12;</code>
     */
    public com.google.protobuf.ByteString
        getTargetJobNameBytes() {
      java.lang.Object ref = targetJobName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetJobName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 eresult = 13 [default = 2];
    public static final int ERESULT_FIELD_NUMBER = 13;
    private int eresult_;
    /**
     * <code>optional int32 eresult = 13 [default = 2];</code>
     */
    public boolean hasEresult() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 eresult = 13 [default = 2];</code>
     */
    public int getEresult() {
      return eresult_;
    }

    // optional string errorMessage = 14;
    public static final int ERRORMESSAGE_FIELD_NUMBER = 14;
    private java.lang.Object errorMessage_;
    /**
     * <code>optional string errorMessage = 14;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string errorMessage = 14;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMessage = 14;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 ip = 15;
    public static final int IP_FIELD_NUMBER = 15;
    private int ip_;
    /**
     * <code>optional uint32 ip = 15;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional uint32 ip = 15;</code>
     */
    public int getIp() {
      return ip_;
    }

    // optional uint32 authAccountFlags = 16;
    public static final int AUTHACCOUNTFLAGS_FIELD_NUMBER = 16;
    private int authAccountFlags_;
    /**
     * <code>optional uint32 authAccountFlags = 16;</code>
     */
    public boolean hasAuthAccountFlags() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional uint32 authAccountFlags = 16;</code>
     */
    public int getAuthAccountFlags() {
      return authAccountFlags_;
    }

    // optional int32 transportError = 17 [default = 1];
    public static final int TRANSPORTERROR_FIELD_NUMBER = 17;
    private int transportError_;
    /**
     * <code>optional int32 transportError = 17 [default = 1];</code>
     */
    public boolean hasTransportError() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 transportError = 17 [default = 1];</code>
     */
    public int getTransportError() {
      return transportError_;
    }

    // optional uint64 messageID = 18 [default = 18446744073709551615];
    public static final int MESSAGEID_FIELD_NUMBER = 18;
    private long messageID_;
    /**
     * <code>optional uint64 messageID = 18 [default = 18446744073709551615];</code>
     */
    public boolean hasMessageID() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional uint64 messageID = 18 [default = 18446744073709551615];</code>
     */
    public long getMessageID() {
      return messageID_;
    }

    // optional uint32 publisherGroupID = 19;
    public static final int PUBLISHERGROUPID_FIELD_NUMBER = 19;
    private int publisherGroupID_;
    /**
     * <code>optional uint32 publisherGroupID = 19;</code>
     */
    public boolean hasPublisherGroupID() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional uint32 publisherGroupID = 19;</code>
     */
    public int getPublisherGroupID() {
      return publisherGroupID_;
    }

    // optional uint32 sysID = 20;
    public static final int SYSID_FIELD_NUMBER = 20;
    private int sysID_;
    /**
     * <code>optional uint32 sysID = 20;</code>
     */
    public boolean hasSysID() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional uint32 sysID = 20;</code>
     */
    public int getSysID() {
      return sysID_;
    }

    // optional uint64 traceTag = 21;
    public static final int TRACETAG_FIELD_NUMBER = 21;
    private long traceTag_;
    /**
     * <code>optional uint64 traceTag = 21;</code>
     */
    public boolean hasTraceTag() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional uint64 traceTag = 21;</code>
     */
    public long getTraceTag() {
      return traceTag_;
    }

    private void initFields() {
      steamID_ = 0L;
      clientSessionID_ = 0;
      routingAppID_ = 0;
      jobIDSource_ = -1L;
      jobIDTarget_ = -1L;
      targetJobName_ = "";
      eresult_ = 2;
      errorMessage_ = "";
      ip_ = 0;
      authAccountFlags_ = 0;
      transportError_ = 1;
      messageID_ = -1L;
      publisherGroupID_ = 0;
      sysID_ = 0;
      traceTag_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed64(1, steamID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, clientSessionID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, routingAppID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFixed64(10, jobIDSource_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFixed64(11, jobIDTarget_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(12, getTargetJobNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(13, eresult_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(14, getErrorMessageBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(15, ip_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt32(16, authAccountFlags_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(17, transportError_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt64(18, messageID_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeUInt32(19, publisherGroupID_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeUInt32(20, sysID_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeUInt64(21, traceTag_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(1, steamID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, clientSessionID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, routingAppID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(10, jobIDSource_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(11, jobIDTarget_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getTargetJobNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, eresult_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getErrorMessageBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, ip_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(16, authAccountFlags_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, transportError_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(18, messageID_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(19, publisherGroupID_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(20, sysID_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(21, traceTag_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.steamcommunity.siplus.steamscreenshots.proto.HeaderProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.internal_static_com_steamcommunity_siplus_steamscreenshots_proto_HeaderProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.internal_static_com_steamcommunity_siplus_steamscreenshots_proto_HeaderProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto.class, com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto.Builder.class);
      }

      // Construct using com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        steamID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientSessionID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        routingAppID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        jobIDSource_ = -1L;
        bitField0_ = (bitField0_ & ~0x00000008);
        jobIDTarget_ = -1L;
        bitField0_ = (bitField0_ & ~0x00000010);
        targetJobName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        eresult_ = 2;
        bitField0_ = (bitField0_ & ~0x00000040);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        ip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        authAccountFlags_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        transportError_ = 1;
        bitField0_ = (bitField0_ & ~0x00000400);
        messageID_ = -1L;
        bitField0_ = (bitField0_ & ~0x00000800);
        publisherGroupID_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        sysID_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        traceTag_ = 0L;
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.internal_static_com_steamcommunity_siplus_steamscreenshots_proto_HeaderProto_descriptor;
      }

      public com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto getDefaultInstanceForType() {
        return com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto.getDefaultInstance();
      }

      public com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto build() {
        com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto buildPartial() {
        com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto result = new com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.steamID_ = steamID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientSessionID_ = clientSessionID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.routingAppID_ = routingAppID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.jobIDSource_ = jobIDSource_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.jobIDTarget_ = jobIDTarget_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.targetJobName_ = targetJobName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.eresult_ = eresult_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.errorMessage_ = errorMessage_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.authAccountFlags_ = authAccountFlags_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.transportError_ = transportError_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.messageID_ = messageID_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.publisherGroupID_ = publisherGroupID_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.sysID_ = sysID_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.traceTag_ = traceTag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto) {
          return mergeFrom((com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto other) {
        if (other == com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto.getDefaultInstance()) return this;
        if (other.hasSteamID()) {
          setSteamID(other.getSteamID());
        }
        if (other.hasClientSessionID()) {
          setClientSessionID(other.getClientSessionID());
        }
        if (other.hasRoutingAppID()) {
          setRoutingAppID(other.getRoutingAppID());
        }
        if (other.hasJobIDSource()) {
          setJobIDSource(other.getJobIDSource());
        }
        if (other.hasJobIDTarget()) {
          setJobIDTarget(other.getJobIDTarget());
        }
        if (other.hasTargetJobName()) {
          bitField0_ |= 0x00000020;
          targetJobName_ = other.targetJobName_;
          onChanged();
        }
        if (other.hasEresult()) {
          setEresult(other.getEresult());
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000080;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasAuthAccountFlags()) {
          setAuthAccountFlags(other.getAuthAccountFlags());
        }
        if (other.hasTransportError()) {
          setTransportError(other.getTransportError());
        }
        if (other.hasMessageID()) {
          setMessageID(other.getMessageID());
        }
        if (other.hasPublisherGroupID()) {
          setPublisherGroupID(other.getPublisherGroupID());
        }
        if (other.hasSysID()) {
          setSysID(other.getSysID());
        }
        if (other.hasTraceTag()) {
          setTraceTag(other.getTraceTag());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.steamcommunity.siplus.steamscreenshots.proto.CommonProtos.HeaderProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional fixed64 steamID = 1;
      private long steamID_ ;
      /**
       * <code>optional fixed64 steamID = 1;</code>
       */
      public boolean hasSteamID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional fixed64 steamID = 1;</code>
       */
      public long getSteamID() {
        return steamID_;
      }
      /**
       * <code>optional fixed64 steamID = 1;</code>
       */
      public Builder setSteamID(long value) {
        bitField0_ |= 0x00000001;
        steamID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 steamID = 1;</code>
       */
      public Builder clearSteamID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        steamID_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 clientSessionID = 2;
      private int clientSessionID_ ;
      /**
       * <code>optional int32 clientSessionID = 2;</code>
       */
      public boolean hasClientSessionID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 clientSessionID = 2;</code>
       */
      public int getClientSessionID() {
        return clientSessionID_;
      }
      /**
       * <code>optional int32 clientSessionID = 2;</code>
       */
      public Builder setClientSessionID(int value) {
        bitField0_ |= 0x00000002;
        clientSessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clientSessionID = 2;</code>
       */
      public Builder clearClientSessionID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientSessionID_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 routingAppID = 3;
      private int routingAppID_ ;
      /**
       * <code>optional uint32 routingAppID = 3;</code>
       */
      public boolean hasRoutingAppID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 routingAppID = 3;</code>
       */
      public int getRoutingAppID() {
        return routingAppID_;
      }
      /**
       * <code>optional uint32 routingAppID = 3;</code>
       */
      public Builder setRoutingAppID(int value) {
        bitField0_ |= 0x00000004;
        routingAppID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 routingAppID = 3;</code>
       */
      public Builder clearRoutingAppID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        routingAppID_ = 0;
        onChanged();
        return this;
      }

      // optional fixed64 jobIDSource = 10 [default = 18446744073709551615];
      private long jobIDSource_ = -1L;
      /**
       * <code>optional fixed64 jobIDSource = 10 [default = 18446744073709551615];</code>
       */
      public boolean hasJobIDSource() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional fixed64 jobIDSource = 10 [default = 18446744073709551615];</code>
       */
      public long getJobIDSource() {
        return jobIDSource_;
      }
      /**
       * <code>optional fixed64 jobIDSource = 10 [default = 18446744073709551615];</code>
       */
      public Builder setJobIDSource(long value) {
        bitField0_ |= 0x00000008;
        jobIDSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 jobIDSource = 10 [default = 18446744073709551615];</code>
       */
      public Builder clearJobIDSource() {
        bitField0_ = (bitField0_ & ~0x00000008);
        jobIDSource_ = -1L;
        onChanged();
        return this;
      }

      // optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];
      private long jobIDTarget_ = -1L;
      /**
       * <code>optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];</code>
       */
      public boolean hasJobIDTarget() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];</code>
       */
      public long getJobIDTarget() {
        return jobIDTarget_;
      }
      /**
       * <code>optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];</code>
       */
      public Builder setJobIDTarget(long value) {
        bitField0_ |= 0x00000010;
        jobIDTarget_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 jobIDTarget = 11 [default = 18446744073709551615];</code>
       */
      public Builder clearJobIDTarget() {
        bitField0_ = (bitField0_ & ~0x00000010);
        jobIDTarget_ = -1L;
        onChanged();
        return this;
      }

      // optional string targetJobName = 12;
      private java.lang.Object targetJobName_ = "";
      /**
       * <code>optional string targetJobName = 12;</code>
       */
      public boolean hasTargetJobName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string targetJobName = 12;</code>
       */
      public java.lang.String getTargetJobName() {
        java.lang.Object ref = targetJobName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          targetJobName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string targetJobName = 12;</code>
       */
      public com.google.protobuf.ByteString
          getTargetJobNameBytes() {
        java.lang.Object ref = targetJobName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetJobName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string targetJobName = 12;</code>
       */
      public Builder setTargetJobName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        targetJobName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetJobName = 12;</code>
       */
      public Builder clearTargetJobName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        targetJobName_ = getDefaultInstance().getTargetJobName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetJobName = 12;</code>
       */
      public Builder setTargetJobNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        targetJobName_ = value;
        onChanged();
        return this;
      }

      // optional int32 eresult = 13 [default = 2];
      private int eresult_ = 2;
      /**
       * <code>optional int32 eresult = 13 [default = 2];</code>
       */
      public boolean hasEresult() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 eresult = 13 [default = 2];</code>
       */
      public int getEresult() {
        return eresult_;
      }
      /**
       * <code>optional int32 eresult = 13 [default = 2];</code>
       */
      public Builder setEresult(int value) {
        bitField0_ |= 0x00000040;
        eresult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 eresult = 13 [default = 2];</code>
       */
      public Builder clearEresult() {
        bitField0_ = (bitField0_ & ~0x00000040);
        eresult_ = 2;
        onChanged();
        return this;
      }

      // optional string errorMessage = 14;
      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string errorMessage = 14;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string errorMessage = 14;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 14;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 14;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 14;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000080);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 14;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        errorMessage_ = value;
        onChanged();
        return this;
      }

      // optional uint32 ip = 15;
      private int ip_ ;
      /**
       * <code>optional uint32 ip = 15;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint32 ip = 15;</code>
       */
      public int getIp() {
        return ip_;
      }
      /**
       * <code>optional uint32 ip = 15;</code>
       */
      public Builder setIp(int value) {
        bitField0_ |= 0x00000100;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 ip = 15;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000100);
        ip_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 authAccountFlags = 16;
      private int authAccountFlags_ ;
      /**
       * <code>optional uint32 authAccountFlags = 16;</code>
       */
      public boolean hasAuthAccountFlags() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional uint32 authAccountFlags = 16;</code>
       */
      public int getAuthAccountFlags() {
        return authAccountFlags_;
      }
      /**
       * <code>optional uint32 authAccountFlags = 16;</code>
       */
      public Builder setAuthAccountFlags(int value) {
        bitField0_ |= 0x00000200;
        authAccountFlags_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 authAccountFlags = 16;</code>
       */
      public Builder clearAuthAccountFlags() {
        bitField0_ = (bitField0_ & ~0x00000200);
        authAccountFlags_ = 0;
        onChanged();
        return this;
      }

      // optional int32 transportError = 17 [default = 1];
      private int transportError_ = 1;
      /**
       * <code>optional int32 transportError = 17 [default = 1];</code>
       */
      public boolean hasTransportError() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 transportError = 17 [default = 1];</code>
       */
      public int getTransportError() {
        return transportError_;
      }
      /**
       * <code>optional int32 transportError = 17 [default = 1];</code>
       */
      public Builder setTransportError(int value) {
        bitField0_ |= 0x00000400;
        transportError_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 transportError = 17 [default = 1];</code>
       */
      public Builder clearTransportError() {
        bitField0_ = (bitField0_ & ~0x00000400);
        transportError_ = 1;
        onChanged();
        return this;
      }

      // optional uint64 messageID = 18 [default = 18446744073709551615];
      private long messageID_ = -1L;
      /**
       * <code>optional uint64 messageID = 18 [default = 18446744073709551615];</code>
       */
      public boolean hasMessageID() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional uint64 messageID = 18 [default = 18446744073709551615];</code>
       */
      public long getMessageID() {
        return messageID_;
      }
      /**
       * <code>optional uint64 messageID = 18 [default = 18446744073709551615];</code>
       */
      public Builder setMessageID(long value) {
        bitField0_ |= 0x00000800;
        messageID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 messageID = 18 [default = 18446744073709551615];</code>
       */
      public Builder clearMessageID() {
        bitField0_ = (bitField0_ & ~0x00000800);
        messageID_ = -1L;
        onChanged();
        return this;
      }

      // optional uint32 publisherGroupID = 19;
      private int publisherGroupID_ ;
      /**
       * <code>optional uint32 publisherGroupID = 19;</code>
       */
      public boolean hasPublisherGroupID() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional uint32 publisherGroupID = 19;</code>
       */
      public int getPublisherGroupID() {
        return publisherGroupID_;
      }
      /**
       * <code>optional uint32 publisherGroupID = 19;</code>
       */
      public Builder setPublisherGroupID(int value) {
        bitField0_ |= 0x00001000;
        publisherGroupID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 publisherGroupID = 19;</code>
       */
      public Builder clearPublisherGroupID() {
        bitField0_ = (bitField0_ & ~0x00001000);
        publisherGroupID_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 sysID = 20;
      private int sysID_ ;
      /**
       * <code>optional uint32 sysID = 20;</code>
       */
      public boolean hasSysID() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional uint32 sysID = 20;</code>
       */
      public int getSysID() {
        return sysID_;
      }
      /**
       * <code>optional uint32 sysID = 20;</code>
       */
      public Builder setSysID(int value) {
        bitField0_ |= 0x00002000;
        sysID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 sysID = 20;</code>
       */
      public Builder clearSysID() {
        bitField0_ = (bitField0_ & ~0x00002000);
        sysID_ = 0;
        onChanged();
        return this;
      }

      // optional uint64 traceTag = 21;
      private long traceTag_ ;
      /**
       * <code>optional uint64 traceTag = 21;</code>
       */
      public boolean hasTraceTag() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional uint64 traceTag = 21;</code>
       */
      public long getTraceTag() {
        return traceTag_;
      }
      /**
       * <code>optional uint64 traceTag = 21;</code>
       */
      public Builder setTraceTag(long value) {
        bitField0_ |= 0x00004000;
        traceTag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 traceTag = 21;</code>
       */
      public Builder clearTraceTag() {
        bitField0_ = (bitField0_ & ~0x00004000);
        traceTag_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.steamcommunity.siplus.steamscreenshots.proto.HeaderProto)
    }

    static {
      defaultInstance = new HeaderProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.steamcommunity.siplus.steamscreenshots.proto.HeaderProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_steamcommunity_siplus_steamscreenshots_proto_HeaderProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_steamcommunity_siplus_steamscreenshots_proto_HeaderProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CommonProtos.proto\0220com.steamcommunity" +
      ".siplus.steamscreenshots.proto\"\211\003\n\013Heade" +
      "rProto\022\017\n\007steamID\030\001 \001(\006\022\027\n\017clientSession" +
      "ID\030\002 \001(\005\022\024\n\014routingAppID\030\003 \001(\r\022)\n\013jobIDS" +
      "ource\030\n \001(\006:\02418446744073709551615\022)\n\013job" +
      "IDTarget\030\013 \001(\006:\02418446744073709551615\022\025\n\r" +
      "targetJobName\030\014 \001(\t\022\022\n\007eresult\030\r \001(\005:\0012\022" +
      "\024\n\014errorMessage\030\016 \001(\t\022\n\n\002ip\030\017 \001(\r\022\030\n\020aut" +
      "hAccountFlags\030\020 \001(\r\022\031\n\016transportError\030\021 " +
      "\001(\005:\0011\022\'\n\tmessageID\030\022 \001(\004:\0241844674407370",
      "9551615\022\030\n\020publisherGroupID\030\023 \001(\r\022\r\n\005sys" +
      "ID\030\024 \001(\r\022\020\n\010traceTag\030\025 \001(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_steamcommunity_siplus_steamscreenshots_proto_HeaderProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_steamcommunity_siplus_steamscreenshots_proto_HeaderProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_steamcommunity_siplus_steamscreenshots_proto_HeaderProto_descriptor,
              new java.lang.String[] { "SteamID", "ClientSessionID", "RoutingAppID", "JobIDSource", "JobIDTarget", "TargetJobName", "Eresult", "ErrorMessage", "Ip", "AuthAccountFlags", "TransportError", "MessageID", "PublisherGroupID", "SysID", "TraceTag", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
